### ISSUE TITLE
Missing build dependencies 

### ISSUE THREAD

**Issue by ianwijma** [flavioislima/HeroicGamesLauncher#115]
Hey! Love the project and would love to help out and after I have installed the project. It was complaining that I did not have snapcraft installed. (Nor had I snapd installed)

I will update the docs as I think is needed if that is alrighty?

**Comment by ianwijma** [comment]
I also noticed when installing the dependencies, the package-lock.json > version was not updated to 1.2.1

**Comment by ianwijma** [comment]
While running `npm run dist` I run into some error which I'm not 100% familiar with.

The error I get is the following: `Please install the 'multipass-sshfs' snap manually inside the instance.`

Full log:
```bash
➜  HeroicGamesLauncher git:(main) ✗ npm run dist

> heroic@1.2.1 dist /home/ian/Code/ianwijma/HeroicGamesLauncher
> npm run build-electron && npm run build && electron-builder -c.extraMetadata.main=build/main.js --linux


> heroic@1.2.1 build-electron /home/ian/Code/ianwijma/HeroicGamesLauncher
> tsc --project electron/tsconfig.json


> heroic@1.2.1 build /home/ian/Code/ianwijma/HeroicGamesLauncher
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  52.61 KB  build/static/js/2.443bbf6a.chunk.js
  9.83 KB   build/static/js/main.51eb4c67.chunk.js
  3.63 KB   build/static/css/main.b7bc13a8.chunk.css
  770 B     build/static/js/runtime-main.08a3e730.js

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

  • electron-builder  version=22.9.1 os=5.8.0-7630-generic
  • loaded configuration  file=package.json ("build" field)
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
  • loaded parent configuration  preset=react-cra
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=11.2.0 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/heroic_1.2.1_amd64.snap
  • building        target=AppImage arch=x64 file=dist/heroic-1.2.1.AppImage
Ignoring '--target-arch' flag.  This flag requires --destructive-mode and is unsupported with Multipass and LXD build providers.
Launching a VM.
mesg: ttyname failed: Inappropriate ioctl for device                            
mesg: ttyname failed: Inappropriate ioctl for device
mount failed: Error enabling mount support in 'snapcraft-heroic'                

Please install the 'multipass-sshfs' snap manually inside the instance.
An error occurred with the instance when trying to mount with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
  ⨯ exit status 2
github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr
        /Volumes/data/Documents/app-builder/pkg/util/exec.go:23
github.com/develar/app-builder/pkg/package-format/snap.buildWithoutTemplate
        /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:345
github.com/develar/app-builder/pkg/package-format/snap.Snap
        /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:199
github.com/develar/app-builder/pkg/package-format/snap.ConfigureCommand.func1
        /Volumes/data/Documents/app-builder/pkg/package-format/snap/snap.go:77
github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
        /Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
        /Volumes/data/Documents/app-builder/main.go:90
runtime.main
        /usr/local/Cellar/go/1.14.5/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14.5/libexec/src/runtime/asm_amd64.s:1373  
  ⨯ /home/ian/Code/ianwijma/HeroicGamesLauncher/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                           Error: /home/ian/Code/ianwijma/HeroicGamesLauncher/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                               at ChildProcess.<anonymous> (/home/ian/Code/ianwijma/HeroicGamesLauncher/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                               at Object.onceWrapper (events.js:421:26)
                                                                                                                                                               at ChildProcess.emit (events.js:314:20)
                                                                                                                                                               at maybeClose (internal/child_process.js:1047:16)
                                                                                                                                                               at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heroic@1.2.1 dist: `npm run build-electron && npm run build && electron-builder -c.extraMetadata.main=build/main.js --linux`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heroic@1.2.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ian/.npm/_logs/2021-01-27T09_27_04_487Z-debug.log

**Comment by Linux4Good** [comment]
I had the same issue, is because you need to run `npm run dist {package that you want to build}`, for instance, for testing I do: `npm run dist AppImage`. If you run only dist, it will build all packages. And for building the snap one you will need multipass and snapcraft. But it is not working so I think we should remove it from the package.json

**Comment by ianwijma** [comment]
Yeah I have started updating the docs, but I got stuck, so need the help of the author to finish it.

**Comment by flavioislima** [comment]
@ianwijma removed the snap part on main branch, now should be fine
