### ISSUE TITLE
Borderlands 3 download

### ISSUE THREAD

**Issue by MrWeedx3** [flavioislima/HeroicGamesLauncher#137]
this error Message appears by downloader Borderlands 3
 Error occurred in handler for 'readFile': Error: EMFILE: too many open files, open '/home/alexander/.config/legendary/user.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at /opt/heroic/resources/app.asar/build/main.js:360:42
    at Generator.next (<anonymous>)
    at /opt/heroic/resources/app.asar/build/main.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/heroic/resources/app.asar/build/main.js:23:12)
    at /opt/heroic/resources/app.asar/build/main.js:353:56 {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: '/home/alexander/.config/legendary/user.json'

**Comment by flavioislima** [comment]
This is happening only with borderlands 3? Can you try installing legendary and installing using it?
