### ISSUE TITLE
Legendary not found in appimage (1.5.0)

### ISSUE THREAD

**Issue by clebercasali** [flavioislima/HeroicGamesLauncher#167]
`Error occurred in handler for 'writeLibrary': Error: Command failed: legendary list-games --json
/bin/sh: 1: legendary: not found

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'legendary list-games --json',
  stdout: '',
  stderr: '/bin/sh: 1: legendary: not found\n'
}
`

**Comment by flavioislima** [comment]
I'm trying to replicate it but for me it is working normally.
Can you try to download again the AppImage?

**Comment by flavioislima** [comment]
Sorry, found the issue. I'll release a hotfix.

**Comment by flavioislima** [comment]
Fixed on 1.5.1 @clebercasali

**Comment by clebercasali** [comment]
It worked! Thank you!
