### ISSUE TITLE
AUR Package Not Working (Black Screen)

### ISSUE THREAD

**Issue by balajsra** [flavioislima/HeroicGamesLauncher#20]
# System Information

- OS: Arch Linux x86_64
- Kernel: 5.10.4-107-tkg-pds
- DE: xinitrc
- WM: dwm
- CPU: Intel i5-6500
- GPU: NVIDIA GeForce GTX 1070
- GPU Driver: NVIDIA 455.45.01

# Software Version Information

- Heroic Games Launcher Version: 0.4.0-1 ([AUR Package](https://aur.archlinux.org/packages/heroic-games-launcher-bin/))
- Electron Version (output of `electron -v`): v11.1.1

# Issue Description

## Main Issue

I installed the AUR package ([heroic-games-launcher-bin](https://aur.archlinux.org/packages/heroic-games-launcher-bin/)) with yay and am finding that the program just loads to a black screen when using the desktop shortcut (see screenshot below).

![image](https://user-images.githubusercontent.com/22876640/103785229-f4aef800-5008-11eb-9688-288ac9bb1331.png)

I found the binary installed at `/opt/heroic` so I directly ran that with `./heroic` and got the same issue, but this time with the following error message.

```
(node:130190) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Error occurred in handler for 'readFile': TypeError: Cannot read property 'url' of undefined
    at /opt/heroic/resources/app.asar/build/main.js:152:15
    at Array.map (<anonymous>)
    at /opt/heroic/resources/app.asar/build/main.js:145:10
    at async electron/js2c/browser_init.js:189:563
```

## Previous Attempts

It should be noted that I attempted to install a previous version of Heroic Games Launcher (I think 0.3 maybe) via the AUR package and was able to login with my epic account. At that point, the program would appear to load my list of games in a spawned terminal, then suddenly close and re-open. When it opened again, the dialog box asking if I wanted to login would appear again. If I clicked yes, it would load my list of games and crash again, then repeat the process. With the current version of the program, it doesn't prompt me to login at all, it just shows a black screen.

# Experimentation

I also tried running the program binary as `sudo ./heroic --no-sandbox` to see if it was an issue relating to my current user. In this case, the program appears to be functioning as expected (see screenshot below). This leads me to believe that my epic login information might be messed up, but is still stored somewhere on my system. Perhaps clearing this would help?

![image](https://user-images.githubusercontent.com/22876640/103786289-4441f380-500a-11eb-9aa5-9db992b50a0d.png)

**Comment by balajsra** [comment]
Issue appears to have been resolved as of AUR package version 0.4.1-1

![image](https://user-images.githubusercontent.com/22876640/103800991-187b3980-501b-11eb-955d-d75bc5c8d351.png)
