### ISSUE TITLE
Games won't launch if wine path contains spaces

### ISSUE THREAD

**Issue by Beanow** [flavioislima/HeroicGamesLauncher#26]
Similar to #13, the `legendary launch` invocation has the `--wine` option with a space in it.

```
Error: Command failed:  /opt/heroic/resources/app.asar.unpacked/build/bin/legendary launch [game] --wine /home/[user]/.steam/root/compatibilitytools.d/Proton 5.13/dist/bin/wine64 --wine-prefix '/mnt/storage/WinePrefix-Heroic'
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching Cobra...
Traceback (most recent call last):
  File "legendary/cli.py", line 1375, in <module>
  File "legendary/cli.py", line 1341, in main
  File "legendary/cli.py", line 512, in launch_game
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/[user]/.steam/root/compatibilitytools.d/Proton'
```

**Comment by Beanow** [comment]
Actually there's a second problem. It's looking for `.../Proton 5.13/dist/bin/wine64` which indeed doesn't exist. Probably needs to be `../Proton 5.13/proton` for proton.

**Comment by flavioislima** [comment]
I see, I'll check and add it to the next release that will be focused on bugfixes.
Thanks for that!

**Comment by flavioislima** [comment]
Fixed on latest release
