### ISSUE TITLE
DXVK install failed, due to using sh on Ubuntu

### ISSUE THREAD

**Issue by Beanow** [flavioislima/HeroicGamesLauncher#83]
After #67's issue, I manually created `~/.config/heroic/Tools/DXVK` using version `dxvk-1.7.3L-03f11ba`.
Next time trying to launch a game, it tries to install but fails to complete.

The terminal outputs:
```
installing DXVK on '/mnt/storage/WinePrefix-Heroic' WINEPREFIX='/mnt/storage/WinePrefix-Heroic' sh /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh install
Error: Command failed: WINEPREFIX='/mnt/storage/WinePrefix-Heroic' sh /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh install
/home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: 31: /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: 0: not found
wine: configuration in L"/mnt/storage/WinePrefix-Heroic" has been updated.
/home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: 83: /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: Bad substitution

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: "WINEPREFIX='/mnt/storage/WinePrefix-Heroic' sh /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh install",
  stdout: '',
  stderr: '/home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: 31: /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: 0: not found\n' +
    'wine: configuration in L"/mnt/storage/WinePrefix-Heroic" has been updated.\n' +
    '/home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: 83: /home/username/.config/heroic/Tools/DXVK/dxvk-1.7.3L-03f11ba/setup_dxvk.sh: Bad substitution\n'
}
```

Looking around I found this answer https://stackoverflow.com/a/20616103 identifies the problem.

> The default shell (/bin/sh) under Ubuntu points to dash, not bash.
> So if you `chmod +x your_script_file.sh` and then run it with `./your_script_file.sh`, or if you run it with `bash your_script_file.sh`, it should work fine.
>
> Running it with `sh your_script_file.sh` will not work because the hashbang line will be ignored and the script will be interpreted by dash, which does not support that string substitution syntax.

Indeed changing `sh` to `bash` works.
As well as removing `sh` (the `setup_dxvk.sh` already has execution permission after extracting it).

**Comment by flavioislima** [comment]
@Beanow just released a fix for it. Upgrade to 1.1.2 and try again.

**Comment by Beanow** [comment]
Tried a new wine prefix and seems to be fixed. :+1:
